steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/mahito/flux/nginx:$SHORT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/mahito/flux/nginx:$TAG_NAME'
    - '.'

images:
- 'gcr.io/$PROJECT_ID/mahito/flux/nginx:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/mahito/flux/nginx:$TAG_NAME'
