---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.nginx: semver:~1.0.0
    fluxcd.io/ignore: true
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/cloudtu-dev-02962067/mahito/flux/nginx:1.0.5
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
